print("Meu\nnome\né\nAnderson")
print("Meu\nnome\né\nAnderson", end = " Matos ")
print("Anderson Matos.")
print("peixe", "chips", sep="&")
print("2")
print(2)
print(0x123)
print(0.0000000000000000000001)
print("Eu gosto \"Monty Python\"")
print('I like "Monty Python"')
print('I\'m Monty Python.')
